### ISSUE TITLE
Blacklisting/revoking JWTs

### ISSUE THREAD

**Issue by fitodic** [Styria-Digital/django-rest-framework-jwt#1]
If a user changes its authentication credentials, e.g. its password, the old token is still valid and the user is not "logged out". This could be a potential security issue when users' accounts are concerned, at least until the tokens expire.

Could we implement a mechanism for revoking/blacklisting JWTs? [django-rest-framework-simplejwt](https://github.com/davesque/django-rest-framework-simplejwt#blacklist-app)'s approach could serve as a good starting point.

**Comment by mjun** [comment]
Yes we can and yes we will :wink:
