### ISSUE TITLE
custom JWT_RESPONSE_PAYLOAD_HANDLER negated by second call to view serializer

### ISSUE THREAD

**Issue by fablet** [Styria-Digital/django-rest-framework-jwt#10]
https://github.com/Styria-Digital/django-rest-framework-jwt/blob/9d97eab9ad3df81e7418b20b6f2a9dea6e489a0b/src/rest_framework_jwt/views.py#L40

The call to self.get_serializer at line 40 in BaseJSONWebTokenAPIView causes the payload created by api_settings.JWT_RESPONSE_PAYLOAD_HANDLER to be run back through the JSONWebTokenSerializer, effectively eliminating anything added to the payload by a custom handler other than the fields in JSONWebTokenSerializer.
For example, the custom payload handler, that I wrote and have been successfully using with the original GetBlimp package, uses "authentication_token", rather than "token" to return the token, and includes some additional pieces of data, but with the new view, the only thing returned by the response is "email".

**Comment by fitodic** [comment]
Yes, we are aware that this for is not entirely backwards-compatible with the original library. This is one of those places where the two packages differ. 

Have you considered overriding the view's serializer to support the extra fields you've added?

**Comment by 3dluis** [comment]
Please approve the merge this this pull request

[Pull Request](https://github.com/Styria-Digital/django-rest-framework-jwt/pull/16)

**Comment by paymog** [comment]
See  #22

**Comment by tchaguitos** [comment]
thanks @paymog :)

**Comment by marcosox** [comment]
> Yes, we are aware that this for is not entirely backwards-compatible with the original library. This is one of those places where the two libraries differ.

Is this thing documented somewhere? I switched libraries and it silently broke my application. At first impression I would consider this a bug, since it negates completely the use of custom payload handlers if I understand correctly.

Anyway, what is the rationale behind this change?

**Comment by tchaguitos** [comment]
@marcosox #16

**Comment by tchaguitos** [comment]
@fitodic @paymog \o/
