### ISSUE TITLE
New release with support for Django 3.2

### ISSUE THREAD

**Issue by GlugovGrGlib** [Styria-Digital/django-rest-framework-jwt#101]
Hi!
We are looking forward to using drf-jwt with Django 3.2

Required PR, for testing against the Django 3.2, was opened, but wasn't merged yet: https://github.com/Styria-Digital/django-rest-framework-jwt/pull/97
Is there any chance a new version will be bumped soon?

If any blockers with the release, I would be happy to help.

Thank you

**Comment by fitodic** [comment]
Sorry for the late response. The PR was merged, but I'm not sure if a new release is necessary. From [setup.cfg](https://github.com/Styria-Digital/django-rest-framework-jwt/blob/master/setup.cfg#L39):
```cfg
PyJWT[crypto]>=1.5.2,<3.0.0
Django>=1.11
djangorestframework>=3.7
```
there's no upper bound so I think you should be able to install it next to Django 3.2. Could you please check it out and confirm?

**Comment by GlugovGrGlib** [comment]
@fitodic Thanks, seems like it working without any problem!
