### ISSUE TITLE
[1.15.0] rest-framework-jwt breaks if blacklist app is not installed

### ISSUE THREAD

**Issue by igadmile** [Styria-Digital/django-rest-framework-jwt#34]
New version forces users to have blacklist app installed even if the feature is not being used.

Eg. of failed test:

> psycopg2.errors.UndefinedTable: relation "rest_framework_jwt_blacklistedtoken" does not exist
E               LINE 1: SELECT (1) AS "a" FROM "rest_framework_jwt_blacklistedtoken"...

I assume the issue is [here](https://github.com/Styria-Digital/django-rest-framework-jwt/blob/master/src/rest_framework_jwt/authentication.py#L70).

It wold be desirable to add a check if the app is installed and only run it if it is.

I can provide a fix if we agree on the solution :smile:

**Comment by lmeyerov** [comment]
Was still seeing issues in the latest `pip`, maybe not pushed yet?

For others who see errors here, simple workaround is:

```
@ -94,6 +94,7 @@
REST_APPS = [
    'rest_framework',
    # 'rest_framework.authtoken',
    'rest_framework_jwt.blacklist', #for djangorestframework_jwt -> drf-jwt==1.15.0
    'django_filters',

]```

**Comment by marcosox** [comment]
Also, a word in the README about having to add `rest_framework_jwt.blacklist` to `INSTALLED_APPS` would be nice.
