### ISSUE TITLE
maintenance status?

### ISSUE THREAD

**Issue by nigoroll** [Styria-Digital/django-rest-framework-jwt#38]
Dear people at Styria,
[this comment](https://github.com/Styria-Digital/django-rest-framework-jwt/pull/37#issuecomment-593931259) suggests that there might not be an active maintainer for this package at the moment.
It would be helpful to get some quick feedback on the maintenance status. If you need any help, please say so.

**Comment by konr4d** [comment]
@ntuckovic, could you comment?

**Comment by ntuckovic** [comment]
@konr4d see a reply in a linked comment in @nigoroll question... thanks for notifying me!

**Comment by nigoroll** [comment]
@konr4d @ntuckovic thank you!
