### ISSUE TITLE
Migrations fail on MySQL

### ISSUE THREAD

**Issue by jmbowman** [Styria-Digital/django-rest-framework-jwt#40]
The migrations for the new `blacklist` app fail because `TextField` can't have a unique constraint in MySQL: https://docs.djangoproject.com/en/2.2/ref/databases/#textfield-limitations .  It fails with:

> BLOB/TEXT column 'token' used in key specification without a key length

For now we can downgrade to 0.14.0 as we don't need the blacklist functionality yet, but this is a blocker for upgrading until not only a new migration fixes the problem, but the existing migration changes to not blow up on MySQL.

**Comment by fitodic** [comment]
Thanks for reporting this :+1: 

Technically, you _can_ upgrade to 1.15+ without registering the `blacklist` app in `INSTALLED_APPS`, but that's not a solution. 

We've opted for a database constraint to avoid race conditions in Python and to avoid cluttering the table with duplicates if a race condition does occur. However, seeing this is an issue on MySQL, we should definitely revisit that decision and possibly allow duplicates in the table, and query for the latest token:

```python
blacklisted_token = BlacklistedToken.objects\
    .filter(token=token)\
    .order_by("-blacklisted_at")\
    .first()
if not blacklisted_token:
    # whatever needs to happen
```

I've never used MySQL for Django apps so you definitely have more experience than I do. Do you have another workaround in mind that would alleviate this situation?

**Comment by feanil** [comment]
@fitodic given the mysql issue, would you be open to putting a constraint in python instead?  One option would be to do a get_or_create which would insure that if the token already exists we just update it which should mitigate most of the duplication issues.

I'm happy to make the change if you think the approach makes sense.

**Comment by fitodic** [comment]
> @fitodic given the mysql issue, would you be open to putting a constraint in python instead? One option would be to do a get_or_create which would insure that if the token already exists we just update it which should mitigate most of the duplication issues.
> 
> I'm happy to make the change if you think the approach makes sense.

Sure. If this is blocking people from using this library on MySQL, then by all means, lets use `get_or_create` instead.

If you have the time to implement this change, I'd be happy to merge it.

**Comment by feanil** [comment]
Created https://github.com/Styria-Digital/django-rest-framework-jwt/pull/58
