### ISSUE TITLE
Install instructions missing "rest_framework_jwt" for installed apps

### ISSUE THREAD

**Issue by tithamane** [Styria-Digital/django-rest-framework-jwt#44]
I tend to follow the installation instructions and had this working before. Now after sometime I tried to use this a different project and it refused to work even though I had followed the instructions.

I had to check an old project to see how I solved it and it turns out that I forgot to add "rest_framework_jwt" in the installed APPS.

Could you maybe add this to you docs for the settings file? Usually when following instructions, it would be good if the thing works without issues.

**Comment by fitodic** [comment]
@tithamane Thanks for reporting this :slightly_smiling_face: Would you like to send a PR that fixes this issue?

**Comment by hvitis** [comment]
@fitodic Created pull for this here:
https://github.com/Styria-Digital/django-rest-framework-jwt/pull/52
