### ISSUE TITLE
Tests with settings monkeypatches failing 

### ISSUE THREAD

**Issue by dominik-bln** [Styria-Digital/django-rest-framework-jwt#47]
It looks like all tests that are using `monkeypatch` to make changes to the `api_settings` recently started to fail. I tried a bit to fix this for the PRs I just opened, but am not completely sure what is causing this, might be some update in a dependency (?).

The only thing related I could find for this is the following issue in `django-rest-framework`:

https://github.com/encode/django-rest-framework/issues/7120

**Comment by dominik-bln** [comment]
See also:

https://github.com/encode/django-rest-framework/pull/7144/files#diff-f9716c39348a77db61afdaa2ed35cd87R194

**Comment by nigoroll** [comment]
FTR see also https://github.com/Styria-Digital/django-rest-framework-jwt/pull/33#issuecomment-617000053 / https://github.com/Styria-Digital/django-rest-framework-jwt/pull/33#issuecomment-617005911
Filip had already mentioned that he wanted to have a look.

**Comment by fitodic** [comment]
@dominik-bln @nigoroll I've fixed it by removing the tests that triggered this unwanted behavior. Feel free to pull these changes into your own branches when you get the chance.
