### ISSUE TITLE
documentation doesn't mention need of INSTALLED_APPS

### ISSUE THREAD

**Issue by radix** [Styria-Digital/django-rest-framework-jwt#55]
I just switched from djangorestframework-jwt to this package, and one of the things I ran into was this error:

```
RuntimeError: Model class rest_framework_jwt.blacklist.models.BlacklistedToken doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

I had to add `rest_framework_jwt` to `INSTALLED_APPS` in order for my code to work. This isn't mentioned anywhere in the documentation.

**Comment by ailionx** [comment]
Same issue here.
