### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'.

### ISSUE THREAD

**Issue by DmytroLitvinov** [Styria-Digital/django-rest-framework-jwt#76]
With new major release of PyJWT v2, we should add compatibility to it.

Helpful link: https://github.com/SimpleJWT/django-rest-framework-simplejwt/pull/329 and all links in it.

**Comment by DmytroLitvinov** [comment]
I don't know who to tag, but I am ready to provide a PR.
Just wanna make sure that it will be reviewed and merged and new minor version will be released.

**Comment by palfrey** [comment]
Fixed by #91 I think?

**Comment by fitodic** [comment]
Possibly. I've released 1.19.0 so anyone who's using it can try it out. I'll close this issue for now. If this issue reappears, feel free to reopen this issue.
