### ISSUE TITLE
Django 2.x

### ISSUE THREAD

**Issue by jayvdb** [Styria-Digital/django-rest-framework-jwt#8]
setup.py lists install requirements `Django>=1.11,<2.0` , however this passes all tests on Django 2.2 at least, and pypi package `django-restframework-jwt` is known to work fairly well on Django 2.0 and 2.1 even now.

Is there any reason not to expand the support matrix to include Django 2.x, with .travis.yml/tox.ini matrixes covering those ?

I think that the lack of stated support for Django 2.x is one of the main reasons people are looking for a maintained drop-in replacement for pypi package `django-restframework-jwt`.

**Comment by jayvdb** [comment]
Patch to get the tests working on Django 2.2

```patch
diff --git a/tests/models.py b/tests/models.py
index aa39915..a15d42f 100644
--- a/tests/models.py
+++ b/tests/models.py
@@ -18,7 +18,8 @@ class UserWithProfile(AbstractUser):


 class UserProfile(models.Model):
-    user = models.OneToOneField(UserWithProfile, related_name='profile')
+    user = models.OneToOneField(UserWithProfile, related_name='profile',
+                                on_delete=models.CASCADE)

     class Meta:
         app_label = 'tests'
```

I've packaged this up for openSUSE at https://build.opensuse.org/package/show/home:jayvdb:django/python-drf-jwt

**Comment by fitodic** [comment]
@jayvdb Thank you for pointing that out. Would you mind sending a pull request that extends the CI support to Django 2+ versions? We are a bit preoccupied at the moment, but I would gladly review and merge the PR.

**Comment by jayvdb** [comment]
Would love to.

Is it ok if I use tox-travis to simplify that task.

https://github.com/barseghyanartur/django-nine/pull/1 is an example of the extra stuff needed because Travis xenial images are needed for Django 2.2 .  (The one for this repo will be a bit simpler because it doesnt support really old Django)

**Comment by fitodic** [comment]
Sure, feel free to use `tox-travis` if that will simplify the configuration.
